### ISSUE TITLE
Blackbone

### ISSUE THREAD

**Issue by LetMeJustDoThis** [haydenpog/dope-ghost-2.0-fixed#2]
where is the blackbone src file? or do i have to make one and also:
![image](https://github.com/haydenpog/dope-ghost-2.0-fixed/assets/105584635/75e6744f-8a7d-4e72-b000-6bda724ff232)

**Comment by LetMeJustDoThis** [comment]
it also searches for a vcxproj file

**Comment by haydenpog** [comment]
https://youtu.be/LHXS-wEXz3Y (HOW TO FIX VIDEO)
