### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by sametdemirrr** [haydenpog/dope-ghost-2.0-fixed#4]
https://github.com/haydenpog/dope-ghost-2.0-fixed/assets/96482435/9c354068-2b81-4911-ae97-f35e85f292f3

**Comment by haydenpog** [comment]
This is an issue with blackbone not dope, please just download an older release of blackbone that has the file or download the newest if you currently have an older version.

https://github.com/DarthTon/Blackbone/pull/505 (here is how someone fixed it b4)

**Comment by sametdemirrr** [comment]
> This is an issue with blackbone not dope, please just download an older release of blackbone that has the file or download the newest if you currently have an older version.
> 
> [DarthTon/Blackbone#505](https://github.com/DarthTon/Blackbone/pull/505) (here is how someone fixed it b4)

tysm

**Comment by sametdemirrr** [comment]
i got again same error
